//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBPayments_Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientPassword
    {
        public string client_id { get; set; }
        public string password { get; set; }
        public System.DateTime date_created { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
