//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace WBPayments_Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int payment_id { get; set; }
        public string client_id { get; set; }
        public int invoice_id { get; set; }
        [Range(0, 99999999)]
        public decimal amount { get; set; }
        public string currency_id { get; set; }
        public System.DateTime date_created { get; set; }
        public string gateway_id { get; set; }
        public string payment_status_id { get; set; }
        [MaxLength(200)]
        public string description { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Gateway Gateway { get; set; }
        public virtual GatewayPaymentData GatewayPaymentData { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual PaymentStatus PaymentStatus { get; set; }
    }
}
