//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBPayments_Logic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wbpaymentsEntities : DbContext
    {
        public wbpaymentsEntities()
            : base("name=wbpaymentsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<ClientPassword> ClientPassword { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<Gateway> Gateway { get; set; }
        public virtual DbSet<GatewayPaymentData> GatewayPaymentData { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<Operation> Operation { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<PaymentStatus> PaymentStatus { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
    }
}
