//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBPayments_API.Service_WBPayments_Reference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreatePaymentObject", Namespace="http://schemas.datacontract.org/2004/07/WBPayments_Logic")]
    [System.SerializableAttribute()]
    public partial class CreatePaymentObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GatewayIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvoiceNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIdField, value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyId {
            get {
                return this.CurrencyIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyIdField, value) != true)) {
                    this.CurrencyIdField = value;
                    this.RaisePropertyChanged("CurrencyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GatewayId {
            get {
                return this.GatewayIdField;
            }
            set {
                if ((object.ReferenceEquals(this.GatewayIdField, value) != true)) {
                    this.GatewayIdField = value;
                    this.RaisePropertyChanged("GatewayId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceNumber {
            get {
                return this.InvoiceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceNumberField, value) != true)) {
                    this.InvoiceNumberField = value;
                    this.RaisePropertyChanged("InvoiceNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnObjectOfint", Namespace="http://schemas.datacontract.org/2004/07/WBPayments_Logic")]
    [System.SerializableAttribute()]
    public partial class ReturnObjectOfint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ErrorMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] InfoMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] SuccessMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] WarnMsgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ErrorMsg {
            get {
                return this.ErrorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMsgField, value) != true)) {
                    this.ErrorMsgField = value;
                    this.RaisePropertyChanged("ErrorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] InfoMsg {
            get {
                return this.InfoMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoMsgField, value) != true)) {
                    this.InfoMsgField = value;
                    this.RaisePropertyChanged("InfoMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] SuccessMsg {
            get {
                return this.SuccessMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.SuccessMsgField, value) != true)) {
                    this.SuccessMsgField = value;
                    this.RaisePropertyChanged("SuccessMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] WarnMsg {
            get {
                return this.WarnMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.WarnMsgField, value) != true)) {
                    this.WarnMsgField = value;
                    this.RaisePropertyChanged("WarnMsg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfirmPaymentObject", Namespace="http://schemas.datacontract.org/2004/07/WBPayments_Logic")]
    [System.SerializableAttribute()]
    public partial class ConfirmPaymentObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GatewayReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GatewayResponseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PaymentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIdField, value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GatewayReference {
            get {
                return this.GatewayReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.GatewayReferenceField, value) != true)) {
                    this.GatewayReferenceField = value;
                    this.RaisePropertyChanged("GatewayReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GatewayResponse {
            get {
                return this.GatewayResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.GatewayResponseField, value) != true)) {
                    this.GatewayResponseField = value;
                    this.RaisePropertyChanged("GatewayResponse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaymentId {
            get {
                return this.PaymentIdField;
            }
            set {
                if ((this.PaymentIdField.Equals(value) != true)) {
                    this.PaymentIdField = value;
                    this.RaisePropertyChanged("PaymentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusId {
            get {
                return this.StatusIdField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusIdField, value) != true)) {
                    this.StatusIdField = value;
                    this.RaisePropertyChanged("StatusId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnObjectOfboolean", Namespace="http://schemas.datacontract.org/2004/07/WBPayments_Logic")]
    [System.SerializableAttribute()]
    public partial class ReturnObjectOfboolean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ErrorMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] InfoMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] SuccessMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] WarnMsgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ErrorMsg {
            get {
                return this.ErrorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMsgField, value) != true)) {
                    this.ErrorMsgField = value;
                    this.RaisePropertyChanged("ErrorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] InfoMsg {
            get {
                return this.InfoMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoMsgField, value) != true)) {
                    this.InfoMsgField = value;
                    this.RaisePropertyChanged("InfoMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] SuccessMsg {
            get {
                return this.SuccessMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.SuccessMsgField, value) != true)) {
                    this.SuccessMsgField = value;
                    this.RaisePropertyChanged("SuccessMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] WarnMsg {
            get {
                return this.WarnMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.WarnMsgField, value) != true)) {
                    this.WarnMsgField = value;
                    this.RaisePropertyChanged("WarnMsg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service_WBPayments_Reference.IService_WBPayments_Logic")]
    public interface IService_WBPayments_Logic {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_WBPayments_Logic/CreatePayment", ReplyAction="http://tempuri.org/IService_WBPayments_Logic/CreatePaymentResponse")]
        WBPayments_API.Service_WBPayments_Reference.ReturnObjectOfint CreatePayment(WBPayments_API.Service_WBPayments_Reference.CreatePaymentObject createPaymentObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_WBPayments_Logic/CreatePayment", ReplyAction="http://tempuri.org/IService_WBPayments_Logic/CreatePaymentResponse")]
        System.Threading.Tasks.Task<WBPayments_API.Service_WBPayments_Reference.ReturnObjectOfint> CreatePaymentAsync(WBPayments_API.Service_WBPayments_Reference.CreatePaymentObject createPaymentObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_WBPayments_Logic/ConfirmPayment", ReplyAction="http://tempuri.org/IService_WBPayments_Logic/ConfirmPaymentResponse")]
        WBPayments_API.Service_WBPayments_Reference.ReturnObjectOfint ConfirmPayment(WBPayments_API.Service_WBPayments_Reference.ConfirmPaymentObject confirmPaymentObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_WBPayments_Logic/ConfirmPayment", ReplyAction="http://tempuri.org/IService_WBPayments_Logic/ConfirmPaymentResponse")]
        System.Threading.Tasks.Task<WBPayments_API.Service_WBPayments_Reference.ReturnObjectOfint> ConfirmPaymentAsync(WBPayments_API.Service_WBPayments_Reference.ConfirmPaymentObject confirmPaymentObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_WBPayments_Logic/ValidateCredentials", ReplyAction="http://tempuri.org/IService_WBPayments_Logic/ValidateCredentialsResponse")]
        WBPayments_API.Service_WBPayments_Reference.ReturnObjectOfboolean ValidateCredentials(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_WBPayments_Logic/ValidateCredentials", ReplyAction="http://tempuri.org/IService_WBPayments_Logic/ValidateCredentialsResponse")]
        System.Threading.Tasks.Task<WBPayments_API.Service_WBPayments_Reference.ReturnObjectOfboolean> ValidateCredentialsAsync(string user, string pass);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService_WBPayments_LogicChannel : WBPayments_API.Service_WBPayments_Reference.IService_WBPayments_Logic, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_WBPayments_LogicClient : System.ServiceModel.ClientBase<WBPayments_API.Service_WBPayments_Reference.IService_WBPayments_Logic>, WBPayments_API.Service_WBPayments_Reference.IService_WBPayments_Logic {
        
        public Service_WBPayments_LogicClient() {
        }
        
        public Service_WBPayments_LogicClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_WBPayments_LogicClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_WBPayments_LogicClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_WBPayments_LogicClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WBPayments_API.Service_WBPayments_Reference.ReturnObjectOfint CreatePayment(WBPayments_API.Service_WBPayments_Reference.CreatePaymentObject createPaymentObject) {
            return base.Channel.CreatePayment(createPaymentObject);
        }
        
        public System.Threading.Tasks.Task<WBPayments_API.Service_WBPayments_Reference.ReturnObjectOfint> CreatePaymentAsync(WBPayments_API.Service_WBPayments_Reference.CreatePaymentObject createPaymentObject) {
            return base.Channel.CreatePaymentAsync(createPaymentObject);
        }
        
        public WBPayments_API.Service_WBPayments_Reference.ReturnObjectOfint ConfirmPayment(WBPayments_API.Service_WBPayments_Reference.ConfirmPaymentObject confirmPaymentObject) {
            return base.Channel.ConfirmPayment(confirmPaymentObject);
        }
        
        public System.Threading.Tasks.Task<WBPayments_API.Service_WBPayments_Reference.ReturnObjectOfint> ConfirmPaymentAsync(WBPayments_API.Service_WBPayments_Reference.ConfirmPaymentObject confirmPaymentObject) {
            return base.Channel.ConfirmPaymentAsync(confirmPaymentObject);
        }
        
        public WBPayments_API.Service_WBPayments_Reference.ReturnObjectOfboolean ValidateCredentials(string user, string pass) {
            return base.Channel.ValidateCredentials(user, pass);
        }
        
        public System.Threading.Tasks.Task<WBPayments_API.Service_WBPayments_Reference.ReturnObjectOfboolean> ValidateCredentialsAsync(string user, string pass) {
            return base.Channel.ValidateCredentialsAsync(user, pass);
        }
    }
}
